version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install requirements.txt

  build:
    commands:
      - echo "running Tests..."
      - echo "building docker image."
      - docker build -t <> .
      - docker push

  post_build:
    commands:
      - echo "Build completed successfully!"

  
